### ISSUE TITLE
bug: enable() immediately shows privacy layer, app unusable

### ISSUE THREAD

**Issue by jkyoutsey** [capacitor-community/privacy-screen#73] opened 2023-09-29 17:11 UTC
**Plugin version:**
^4.2.0

**Platform(s):**
iOS/Android

**Current behavior:**
Upon calling PrivacyScreen.enable() the privacy layer is immediately displayed making the app unusable. 

**Expected behavior:**
The privacy layer should only be shown when the user is trying to take a screenshot, screen recording, or viewing the task switcher.

**Steps to reproduce:**
[Sample Repo](https://github.com/jkyoutsey/capacitor-community-privacy-screen-demo)

1. Clone and follow instructions to install and run for either iOS/Android.
2. Run on a simulator/real device.
3. Click the "Enable" button.
4. See that the privacy screen is shown and cannot be dismissed.

**Related code:**
See [this file in the repo](https://github.com/jkyoutsey/capacitor-community-privacy-screen-demo/blob/main/src/app/modules/privacy-screen/privacy-screen.page.ts) on line 20 where PrivacyScreen.enable() is called.

**Capacitor doctor:**
```
💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.4.1
  @capacitor/core: 5.4.1
  @capacitor/android: 5.4.1
  @capacitor/ios: 5.4.1

Installed Dependencies:

  @capacitor/cli: 5.3.0
  @capacitor/core: 5.3.0
  @capacitor/android: 5.3.0
  @capacitor/ios: 5.3.0

[success] iOS looking great! 👌
```

**Comment by robingenz** [comment] 2023-09-30 06:52
Thank you for your request.
Please share a screen recording.

**Comment by mirzadugum** [comment] 2023-10-03 08:08
Hello,
This only occurs on iOS17 with custom image added. If you remove splash than its working

**Comment by jkyoutsey** [comment] 2023-10-03 14:36
I did this without splash and had the same results that the screen is blanked out.

Help me understand. When I call enable() is it supposed to show the privacy screen immediately? The documentation suggests that you use enable to _**protect**_ against screenshots and view in the switcher _**if**_ the user tries to take a screenshot/use the switcher. So, enable() = "wait until a screenshot is taken or the switcher is shown and then show privacy screen". Right? Because when I call enable() it IMMEDIATELY blanks my screen, which seems incorrect to me.

But, maybe I misunderstand. Do I need to add listeners and then only call enable() when the listeners are triggered?  "enable" to me != "show". It "enables" protection.

Here is a screen recording where I show it disabled first, then enabled second, all without imageName specified in the config (no splash)


https://github.com/capacitor-community/privacy-screen/assets/3846466/b882b202-72a2-4ddd-a672-721085c0c4ca

**Comment by mirzadugum** [comment] 2023-10-04 08:08
On this video you posted it is working as it should. They grey screen you get it is because you didnt add splashscreen. The privacy screen is visible only when app isnt active (in recent).

**Comment by jkyoutsey** [comment] 2023-10-04 12:14
Yes, it does seem to be working for "recents"/"switcher". But it's NOT preventing screenshots. I couldn't care less about the switcher. I NEED to prevent screenshots. How do you prevent a screenshot with this plugin?

**Comment by robingenz** [comment] 2023-10-04 12:34
I will take a look at it in the next few days.

**Comment by robingenz** [comment] 2023-10-08 15:35
I close this issue as duplicate of #74.

**Closed** 2023-10-08 15:35 UTC
Labels: needs: triage
