### ISSUE TITLE
bug: app crashes on iOS when changing screen orientation

### ISSUE THREAD

**Issue by aljadan** [capacitor-community/privacy-screen#65] opened 2023-08-26 09:04 UTC
**Plugin version:**
4.1.1

**Platform(s):**
iOS

**Current behavior:**
When I enable the plugin on an iOS device and subsequently change the screen orientation, the app crashes. However, if I enable the plugin more than once, it functions correctly without any crash.

**Expected behavior:**
The app should not crash after enabling the plugin

**Steps to reproduce:**
***Scenario 1: App Crash***

Enable the plugin on an iOS device.
Change the screen orientation.
Observe that the app crashes.

***Scenario 2: No Crash***

Enable the plugin on an iOS device.
Disable the plugin.
Re-enable the plugin.
Change the screen orientation.
Notice that the app works fine without any crash.

https://github.com/capacitor-community/privacy-screen/assets/111672775/40f168a4-fd06-450b-85b8-060f903e229a

**Comment by robingenz** [comment] 2023-08-26 17:32
Thank you for your request.
Please provide a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) using [this template](https://github.com/capawesome-team/.capacitor-app) in a public GitHub repository so I can debug the issue.

**Comment by aljadan** [comment] 2023-08-26 21:12
> Thank you for your request. Please provide a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) using [this template](https://github.com/capawesome-team/.capacitor-app) in a public GitHub repository so I can debug the issue.

[Example](https://github.com/aljadan/.capacitor-app)

**Comment by robingenz** [comment] 2023-08-27 14:59
Thank you, I will test this next week and get back to you.

**Comment by robingenz** [comment] 2023-09-02 09:30
Okay, i just tested it and close this issue as a duplicate of #64.

**Closed by robingenz** 2023-09-02 09:30 UTC
Labels: bug/fix, platform: ios, needs: reproduction, needs: triage
